# yaml-language-server: $schema=https://raw.githubusercontent.com/Luftfartsverket/reqstool-client/main/src/reqstool/resources/schemas/v1/requirements.schema.json

metadata:
  urn: reqstool-python-poetry-plugin
  variant: microservice
  title: Reqstool client
  url: https://github.com/Luftfartsverket/reqstool-python-poetry-plugin

requirements:
  - id: POETRY_PLUGIN_001
    title: Support poetry build system for use with reqstool
    significance: shall
    description: Support reqstool to be used with poetry, i.e. creating a sdist tarball with reqstool files.
    categories: [functional-suitability]
    revision: 0.0.1
