name: Lint (black and flake8)
on:
  workflow_dispatch:
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install and configure Poetry (this should ideally be done from pyproject.toml but..)
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: true
          # virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install --with dev
      - name: Run black formatter check
        run: poetry run black --check --verbose src tests
      - name: Run flake8 linter
        run: poetry run flake8
